{
 "title": "Livepatch Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Percentile", "query": "50, 75, 80, 85, 90, 95" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP 200 [10m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_http_request_duration_seconds_count{code=\"200\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP 204 [10m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_http_request_duration_seconds_count{code=\"204\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP 401 [10m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_http_request_duration_seconds_count{code=\"401\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP 403 [10m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_http_request_duration_seconds_count{code=\"403\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP 404 [10m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_http_request_duration_seconds_count{code=\"404\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Livepatch Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_http_request_duration_seconds_count{}[$__rate_interval])) by (handler, method, code) ",
     "legendFormat": "{{code}} - {{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Increase In Database Errors [10m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepatch_server_database_error_count{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "${Percentile}th Percentile[10m]: /v1/client Response Times",
   "type": "graph",
   "description": "Displays the 95th percentile of requests handled under the the Y axis(in seconds).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.${Percentile}, \n    sum(\n        rate(\n            livepatch_server_http_request_duration_seconds_bucket{handler=~\"/v1/client/.*\"}[$__rate_interval]\n        )\n    ) by (le, handler,code)\n)"
    }
   ]
  },
  {
   "title": "${Percentile}th Percentile[10m]: DB Response Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.${Percentile}, \n    sum(\n        rate(\n            livepatch_server_database_query_duration_seconds_bucket{method!~\"^KPI.*\"}[$__rate_interval]\n        )\n    ) by (le, method)\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "${Percentile}th Percentile[10m]: Auth Timings ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.${Percentile}, \n    sum(\n        rate(\n            livepatch_server_http_auth_duration_seconds_bucket{}[$__rate_interval]\n        )\n    ) by (le, token_type)\n)",
     "legendFormat": "{{token_type}}"
    }
   ]
  },
  {
   "title": "${Percentile}th Percentile[10m]: DB KPI Response Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.${Percentile}, \n    sum(\n        rate(\n            livepatch_server_database_query_duration_seconds_bucket{method=~\"^KPI.*$\"}[$__rate_interval]\n        )\n    ) by (le, method)\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Token Usage",
   "type": "graph",
   "description": "This graph represents how many times each token type was used over a 24h period. \nMachine tokens are used when a client authenticated with an auth token checks in.\nResource tokens are used when a client authenticated with ua-contracts checks in.\nAuth tokens are used whenever a new client is registered using old style auth tokens.\nSync tokens are used whenever an on-prem server syncs patches, on-prem servers can also sync via resource tokens.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepatch_server_http_authorizer_count{}[24h])) by (token)",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Contracts Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Contracts Errors",
   "type": "graph",
   "description": "Errors from the contracts service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepatch_server_contracts_error_count{}[$__rate_interval]))",
     "legendFormat": "client errors"
    }
   ]
  },
  {
   "title": "Contracts Response Errors",
   "type": "graph",
   "description": "Reasons why a client was reject from the contracts server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepatch_server_contracts_error_reported_count{}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Cache Info - Patches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Patch Info Cache Hits",
   "type": "graph",
   "description": "The number of cache hits over the last 10 minutes summed over all the Livepatch server units.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepatch_server_patch_cache_hits{}[$__rate_interval]))",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Patch Info Cache Misses",
   "type": "graph",
   "description": "The number of cache misses over the last 10 minutes summed over all the Livepatch server units.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepatch_server_patch_cache_misses{}[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Patch Info Cache Evictions",
   "type": "graph",
   "description": "The number of cache evictions over the last 10 minutes summed over all the Livepatch server units.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepatch_server_patch_cache_evictions{}[$__rate_interval]))",
     "legendFormat": "Evictions"
    }
   ]
  },
  {
   "title": "Patch Info Cache Length",
   "type": "graph",
   "description": "The cache length on each unit",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "livepatch_server_patch_cache_length{}"
    }
   ]
  },
  {
   "title": "Supported Kernels ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Increase[60m]: Unknown Kernel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepatch_client_updates_with_unknown_kernel_total{}[60m]))"
    }
   ]
  },
  {
   "title": "Increase[60m]: Kernel Lib Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepatch_logging_kernels_error_total{}[60m]))"
    }
   ]
  },
  {
   "title": "Increase[60]: Missing Build Date",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepatch_client_updates_without_build_date_total{}[60m]))"
    }
   ]
  },
  {
   "title": "Test Area",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Endpoints Timings ${Percentile}th percentile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.${Percentile}, \n    sum(\n        rate(\n            livepatch_server_http_request_duration_seconds_bucket{}[$__rate_interval]\n        )\n    ) by (le, handler)\n)"
    }
   ]
  },
  {
   "title": "All Database Timings ${Percentile}th percentile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.${Percentile}, \n    sum(\n        rate(\n            livepatch_server_database_query_duration_seconds_bucket{}[$__rate_interval]\n        )\n    ) by (le, method)\n)"
    }
   ]
  }
 ]
}