name: Integration tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      # To speed up the tests, we build the charm with Charmcraft and put the
      # `.charm` file in the repository root directory. Integration tests will
      # pick up this file and avoid building it per test case.
      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic
      - name: Build charm
        run: charmcraft pack --destructive-mode --verbosity=trace

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          channel: 1.28-strict/stable
          juju-channel: 3.4/stable
          provider: microk8s
          microk8s-group: snap_microk8s
          microk8s-addons: "ingress storage dns rbac registry"
      # Instructions from https://microk8s.io/docs/registry-private
      # and https://github.com/containerd/cri/blob/master/docs/registry.md
      # Bash explanation https://stackoverflow.com/questions/15429330/how-to-specify-a-multi-line-shell-variable#comment21828145_15429426
      - name: Setup microk8s for private registry
        run: |
          read -r -d '' REGISTRY_CONFIG << EOL || true
            [plugins."io.containerd.grpc.v1.cri".registry.configs."ghcr.io".auth]
              username = "${{ github.actor }}"
              password = "${{ secrets.GITHUB_TOKEN }}"
          EOL
          echo "$REGISTRY_CONFIG" | sudo tee -a /var/snap/microk8s/current/args/containerd-template.toml
          sudo snap restart microk8s.daemon-containerd
      - name: Install tox
        run: python -m pip install tox
      - name: Run integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: tox -e integration
      - name: Dump logs
        if: failure()
        uses: canonical/charming-actions/dump-logs@main
